name: Lux Urban
favicon: null
layout_spectrum: 0.12233462883159518
typography_spectrum: 0.6947166682220995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5133929667063057
  lightness: 0.4678255571052432
  saturation: 0.9216736843809485
  rhythmicContrast: 0.6833293968811631
purpose: []
